rules_file:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco_rules.local.yaml
  - /etc/falco/rules.d


engine:
  kind: kmod
  kmod:
    buf_size_preset: 4
    drop_failed_exit: false
  ebpf:
    probe: /root/.falco/falco-bpf.o
    buf_size_preset: 4
    drop_failed_exit: false
  modern_ebpf:
    cpus_for_each_buffer: 2
    buf_size_preset: 4
    drop_failed_exit: false
  replay:
    capture_file: ""
  gvisor:
    config: ""
    root: ""

stdout_output:
  enabled: true

json_output: true

http_output:
  enabled: true
  url: http://falcosidekick:2801/
  user_agent: "falcosecurity/falco"
  insecure: true
  ca_cert: ""
  ca_bundle: ""
  ca_path: "/etc/ssl/certs"
  mtls: false
  client_cert: "/etc/ssl/certs/client.crt"
  client_key: "/etc/ssl/certs/client.key"
  echo: false
